#!/usr/bin/env bash
#
# Build the hkjn/gpg Docker images.
#
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="gpg"
CPU_ARCH="$(uname -m)"
BASEIMAGE=hkjn/alpine:${CPU_ARCH}
BUILD_DIR="$(mktemp -d)"
TAG="$DOCKER_USER/$DOCKER_IMAGE:$CPU_ARCH"

echo "Building $TAG in $BUILD_DIR.."
sed "s|ARG_FROM|${BASEIMAGE}|g" Dockerfile.in > $BUILD_DIR/Dockerfile
docker build -t $TAG $BUILD_DIR
NO_PUSH=${NO_PUSH:-""}
if [[ ! "$NO_PUSH" ]]; then
  docker push ${TAG}
fi

